### PR TITLE
Modernize repo (details in description)

### PR DESCRIPTION
**Pull request by jasnow**
Modernize repo by doing the following:
 * Added 2.2.4 and 2.3.0 to .travis.yml.
 * Added "cache: bundler" and "sudo: false" to .travis.yml as suggested by TravisCI guidelines.
   * https://docs.travis-ci.com/user/migrating-from-legacy
 * Changed "http" to "https" in Gemfile.
 * Removed limits on rspec in Gemfile so it would use newer version of gem. Upgraded assert in spec to use new expect format.
 * Moved rake gem into gemspec file to fix 1.8.7 build on TravisCI.

### CODE REVIEW

**Comment by jasnow** [comment]
#26 - Appears my PR overlaps with yours and I did not notice until after I did my changes. Sorry.

**Comment by jasnow** [comment]
@eval - Anything else I need to do for you to merge my PR?

**Comment by jasnow** [comment]
Appears to be no interest in this PR so closing. Welcome to reopen later if you wish.

**Comment by mshibuya** [comment]
@eval I definitely need this for making [RailsAdmin](https://github.com/sferik/rails_admin) compatible with Rails 5.
What can I do to get this merged in? Want some help for maintenance?

**Comment by eval** [comment]
Thanks for the PR and sorry that this took so long.
I released a beta-version - please let me know if there are any issues still with Rails 5.

**Comment by jasnow** [comment]
Super glad to help - Cheers!

**Comment by mshibuya** [comment]
Thank you so much 😍

**Comment by eval** [comment]
and v1.0 is out of the door 🚢

**Pull request merged**
